const express = require('express');
const router = express.Router();
const axios = require('axios');
const { getClients, getClientById, getClientTimezone } = require('../services/config');
const { getFbHierarchy } = require('../services/fb');
const { getCocHierarchy, getCocCampaignTotals, importClick, importLead } = require('../services/coc');
const { mergeHierarchy } = require('../services/merger');
const googleSvc = require('../services/google');
const { toggleCheckboxLine, appendOpenItem, appendOpenItems } = require('../services/markdown');

// GET /api/clients
router.get('/clients', (req, res) => {
  const clients = getClients().map(c => ({
    id: c.id,
    name: c.name,
    timezone: getClientTimezone(c),
    adAccounts: c.adAccounts.map(a => ({
      fbAdAccountId: a.fbAdAccountId,
      cocCampaignId: a.cocCampaignId,
      cocCampaignName: a.cocCampaignName,
      cppTarget: a.cppTarget || null
    }))
  }));
  res.json({ clients });
});

// GET /api/agents — control-panel metadata for the Launchpad Agents panel.
// Static JSON generated by scripts/gen-agents.mjs from the 2by4-agents repo
// (re-run + commit when agents change). Each "Work →" opens a claude.ai/code
// cloud session scoped to that agent.
router.get('/agents', (req, res) => {
  try {
    const data = require('../data/agents.json');
    res.json(data);
  } catch (e) {
    res.status(500).json({ error: 'agents.json missing — run `node scripts/gen-agents.mjs`' });
  }
});

// POST /api/coc/lead — capture a Bagger's Corner opt-in as a Checkout Champ
// partial lead (Import Click → Import Lead), so leads aren't lost when checkout
// is abandoned. The lander (Vercel, no static egress IP) proxies through here
// because all CoC access must originate from Dash's whitelisted IP.
// Gated by dashAuth. Creds in BC_COC_LOGIN_ID / BC_COC_PASSWORD / BC_COC_CAMPAIGN_ID.
router.post('/coc/lead', async (req, res) => {
  const loginId = process.env.BC_COC_LOGIN_ID;
  const password = process.env.BC_COC_PASSWORD;
  const campaignId = process.env.BC_COC_CAMPAIGN_ID;
  // Not configured yet → tell the caller so it falls back to prefill-only.
  if (!loginId || !password || !campaignId) {
    return res.json({ ok: false, configured: false });
  }

  const {
    firstName = '', lastName = '', emailAddress = '', phoneNumber = '',
    answers, ipAddress,
  } = req.body || {};

  if (!emailAddress && !phoneNumber) {
    return res.status(400).json({ ok: false, error: 'missing_contact' });
  }

  try {
    // Open a session so the lead (and any later order) are linked in CoC.
    const sessionId = await importClick(loginId, password, campaignId, { ipAddress });
    await importLead(loginId, password, campaignId, {
      firstName, lastName, emailAddress, phoneNumber, ipAddress,
      sessionId: sessionId || undefined,
      custom: answers || undefined,
    });
    res.json({ ok: true, sessionId: sessionId || null });
  } catch (err) {
    console.error('[coc/lead] import failed:', err.message);
    res.status(502).json({ ok: false, error: 'coc_failed' });
  }
});

// GET /api/dashboard/:clientId?startDate=YYYY-MM-DD&endDate=YYYY-MM-DD
router.get('/dashboard/:clientId', async (req, res) => {
  const { clientId } = req.params;
  const { startDate, endDate } = req.query;

  if (!startDate || !endDate) {
    return res.status(400).json({ error: 'startDate and endDate are required (YYYY-MM-DD)' });
  }

  const client = getClientById(clientId);
  if (!client) return res.status(404).json({ error: `Client "${clientId}" not found` });

  const results = [];
  const errors = [];

  await Promise.all(client.adAccounts.map(async (adAccount) => {
    try {
      const [fbData, cocTotals] = await Promise.all([
        getFbHierarchy(client.fbAccessToken, adAccount.fbAdAccountId, startDate, endDate),
        getCocCampaignTotals(client.cocLoginId, client.cocPassword, adAccount.cocCampaignId, startDate, endDate)
      ]);

      const fbCampaignNames = fbData.map(c => c.name);
      const cocHierarchy = await getCocHierarchy(
        client.cocLoginId, client.cocPassword,
        adAccount.cocCampaignId, startDate, endDate,
        fbCampaignNames
      );

      const merged = mergeHierarchy(fbData, cocHierarchy, adAccount);
      merged.cocTotals = cocTotals;
      results.push(merged);
    } catch (err) {
      console.error(`Error for ${adAccount.fbAdAccountId}:`, err.message);
      errors.push({ fbAdAccountId: adAccount.fbAdAccountId, cocCampaignName: adAccount.cocCampaignName, error: err.message });
    }
  }));

  results.sort((a, b) => a.cocCampaignName.localeCompare(b.cocCampaignName));
  res.json({ clientId, clientName: client.name, timezone: getClientTimezone(client), startDate, endDate, adAccounts: results, errors: errors.length > 0 ? errors : undefined });
});

// ============================================================
// DEBUG - hit these in browser to see raw COC responses
// /api/debug/coc/client1?campaignId=1&startDate=2024-02-20&endDate=2024-02-20
// /api/debug/coc-leads/client1?campaignId=1&startDate=2024-02-20&endDate=2024-02-20
// ============================================================
router.get('/debug/coc/:clientId', async (req, res) => {
  const client = getClientById(req.params.clientId);
  if (!client) return res.status(404).json({ error: 'Client not found' });

  const { campaignId, startDate, endDate } = req.query;
  if (!campaignId || !startDate || !endDate) {
    return res.status(400).json({ error: 'Required: campaignId, startDate (YYYY-MM-DD), endDate (YYYY-MM-DD)' });
  }

  // COC date format: M/D/YY
  function fmtDate(d) {
    const [y, m, day] = d.split('-');
    return `${parseInt(m)}/${parseInt(day)}/${y}`;
  }

  const baseParams = { loginId: client.cocLoginId, password: client.cocPassword, campaignId, startDate: fmtDate(startDate), endDate: fmtDate(endDate) };

  const endpoints = [
    { name: 'transactions/query (SALE+SUCCESS)', params: { ...baseParams, txnType: 'SALE', responseType: 'SUCCESS' } },
    { name: 'transactions/query (all)', params: baseParams },
    { name: 'leads/query', params: baseParams },
    { name: 'order/query', params: baseParams },
  ];

  const results = {};
  for (const ep of endpoints) {
    try {
      const r = await axios.get(`https://api.checkoutchamp.com/${ep.name.split(' ')[0]}`, { params: ep.params });
      results[ep.name] = { status: r.status, data: r.data };
    } catch (err) {
      results[ep.name] = { status: err.response?.status || 'error', error: err.response?.data || err.message };
    }
  }

  res.json({ campaignId, dateRange: `${startDate} → ${endDate}`, results });
});


// GET /api/debug/orders/:clientId?campaignId=X&startDate=YYYY-MM-DD&endDate=YYYY-MM-DD
// Fetches ALL orders with no status/type filter and breaks down counts by orderStatus x orderType
// Use this to diagnose why dashboard purchase count differs from COC
router.get('/debug/orders/:clientId', async (req, res) => {
  const client = getClientById(req.params.clientId);
  if (!client) return res.status(404).json({ error: 'Client not found' });

  const { campaignId, startDate, endDate } = req.query;
  if (!campaignId || !startDate || !endDate) {
    return res.status(400).json({ error: 'Required: campaignId, startDate (YYYY-MM-DD), endDate (YYYY-MM-DD)' });
  }

  function fmtDate(d) {
    const [y, m, day] = d.split('-');
    return `${parseInt(m)}/${parseInt(day)}/${y}`;
  }

  // Fetch all orders — no status or type filter
  let allOrders = [];
  let page = 1;
  let totalResults = null;
  try {
    while (true) {
      const r = await axios.get('https://api.checkoutchamp.com/order/query/', {
        params: {
          loginId: client.cocLoginId,
          password: client.cocPassword,
          campaignId,
          startDate: fmtDate(startDate),
          endDate: fmtDate(endDate),
          resultsPerPage: 200,
          page,
        }
      });
      const data = r.data;
      if (data.result !== 'SUCCESS') { break; }
      const msg = data.message;
      if (totalResults === null) totalResults = msg.totalResults || 0;
      const records = msg.data || [];
      allOrders = allOrders.concat(records);
      if (allOrders.length >= totalResults || records.length === 0) break;
      page++;
    }
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }

  // Break down by orderStatus x orderType
  const byStatus = {};
  const byType = {};
  const byStatusAndType = {};

  for (const o of allOrders) {
    const status = o.orderStatus || 'UNKNOWN';
    const type = o.orderType || 'UNKNOWN';
    const key = `${status} / ${type}`;

    byStatus[status] = (byStatus[status] || 0) + 1;
    byType[type] = (byType[type] || 0) + 1;
    byStatusAndType[key] = (byStatusAndType[key] || 0) + 1;
  }

  // What our dashboard counts (COMPLETE + NEW_SALE)
  const dashboardCount = allOrders.filter(o => o.orderStatus === 'COMPLETE' && o.orderType === 'NEW_SALE').length;
  const totalFetched = allOrders.length;

  res.json({
    clientId: req.params.clientId,
    campaignId,
    dateRange: `${startDate} → ${endDate}`,
    totalResults,
    totalFetched,
    dashboardCounts: dashboardCount,
    gap: totalFetched - dashboardCount,
    breakdown: {
      byStatus,
      byType,
      byStatusAndType,
    },
    // Full order list for manual inspection (orderId, status, type, amount)
    orders: allOrders.map(o => ({
      orderId: o.orderId,
      orderStatus: o.orderStatus,
      orderType: o.orderType,
      totalAmount: o.totalAmount,
      dateCreated: o.dateCreated,
      UTMCampaign: o.UTMCampaign,
    })),
  });
});

// Revenue debug endpoint
router.get('/debug/revenue/:clientId', async (req, res) => {
  try {
    const client = getClientById(req.params.clientId);
    const { campaignId, startDate, endDate } = req.query;
    const axios = require('axios');
    
    function fmtDate(d) {
      const [y, m, day] = d.split('-');
      return `${parseInt(m)}/${parseInt(day)}/${y}`;
    }
    
    const account = client.adAccounts.find(a => String(a.cocCampaignId) === String(campaignId));
    
    // Fetch all COMPLETE orders
    const r = await axios.get('https://api.checkoutchamp.com/order/query/', {
      params: {
        loginId: client.cocLoginId,
        password: client.cocPassword,
        campaignId,
        startDate: fmtDate(startDate),
        endDate: fmtDate(endDate),
        orderStatus: 'COMPLETE',
        orderType: 'NEW_SALE',
        resultsPerPage: 200,
      }
    });

    const orders = r.data.message?.data || [];
    const totalRevenue = orders.reduce((sum, o) => sum + parseFloat(o.totalAmount || 0), 0);
    const nullAmounts = orders.filter(o => !o.totalAmount || o.totalAmount === null).length;
    const orderSummary = orders.map(o => ({
      orderId: o.orderId,
      totalAmount: o.totalAmount,
      baseShipping: o.baseShipping,
      salesTax: o.salesTax,
      surcharge: o.surcharge,
      shipUpcharge: o.shipUpcharge,
      combined: (parseFloat(o.totalAmount||0) + parseFloat(o.baseShipping||0) + parseFloat(o.salesTax||0) + parseFloat(o.surcharge||0) + parseFloat(o.shipUpcharge||0)).toFixed(2),
    })).filter(o => parseFloat(o.baseShipping||0) > 0 || parseFloat(o.surcharge||0) > 0 || parseFloat(o.shipUpcharge||0) > 0);
    
    const totalWithAll = orders.reduce((sum, o) => 
      sum + parseFloat(o.totalAmount||0) + parseFloat(o.baseShipping||0) + parseFloat(o.salesTax||0) + parseFloat(o.surcharge||0) + parseFloat(o.shipUpcharge||0), 0);
    
    const totalShipping = orders.reduce((sum, o) => sum + parseFloat(o.baseShipping||0), 0);
    const totalSurcharge = orders.reduce((sum, o) => sum + parseFloat(o.surcharge||0), 0);
    const totalShipUpcharge = orders.reduce((sum, o) => sum + parseFloat(o.shipUpcharge||0), 0);
    
    res.json({ 
      totalOrders: orders.length,
      totalRevenue: totalRevenue.toFixed(2),
      totalRevenueWithAll: totalWithAll.toFixed(2),
      breakdown: {
        totalAmount: totalRevenue.toFixed(2),
        totalShipping: totalShipping.toFixed(2),
        totalSurcharge: totalSurcharge.toFixed(2),
        totalShipUpcharge: totalShipUpcharge.toFixed(2),
      },
      nonZeroOrders: orderSummary 
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// GET /api/insights/:clientId?date=YYYY-MM-DD
// Returns CPP trend analysis: yesterday vs 7-day rolling avg
// Flags adsets/ads with CPP rising >15% and spend >$25
router.get('/insights/:clientId', async (req, res) => {
  const client = getClientById(req.params.clientId);
  if (!client) return res.status(404).json({ error: 'Client not found' });

  const { date } = req.query;
  if (!date) return res.status(400).json({ error: 'date (YYYY-MM-DD) required' });

  const d = new Date(date + 'T12:00:00Z');
  const yesterday = date;
  const sevenDaysAgo = new Date(d);
  sevenDaysAgo.setDate(d.getDate() - 6);
  const sevenDayStart = sevenDaysAgo.toISOString().split('T')[0];

  try {
    const accountResults = await Promise.all(client.adAccounts.map(async (adAccount) => {
      const [fbYest, fbWeek] = await Promise.all([
        getFbHierarchy(client.fbAccessToken, adAccount.fbAdAccountId, yesterday, yesterday),
        getFbHierarchy(client.fbAccessToken, adAccount.fbAdAccountId, sevenDayStart, yesterday),
      ]);

      const fbCampaignNames = fbWeek.map(c => c.name);
      const [cocYest, cocWeek] = await Promise.all([
        getCocHierarchy(client.cocLoginId, client.cocPassword, adAccount.cocCampaignId, yesterday, yesterday, fbCampaignNames),
        getCocHierarchy(client.cocLoginId, client.cocPassword, adAccount.cocCampaignId, sevenDayStart, yesterday, fbCampaignNames)
      ]);

      const mergedYest = mergeHierarchy(fbYest, cocYest, adAccount);
      const mergedWeek = mergeHierarchy(fbWeek, cocWeek, adAccount);

      // Account-level 7D avg CPP as baseline
      const accountWeekSpend = mergedWeek.fbSpend;
      const accountWeekSales = mergedWeek.campaigns.reduce((sum, c) => sum + (c.cocData?.sales || 0), 0);
      const accountAvgCpp = accountWeekSales > 0 ? accountWeekSpend / accountWeekSales : 0;

      const flagged = [];

      for (const campaign of mergedYest.campaigns) {
        const weekCampaign = mergedWeek.campaigns.find(c => c.name === campaign.name);

        for (const adset of campaign.adsets || []) {
          const weekAdset = weekCampaign?.adsets?.find(a => a.name === adset.name);
          const yestCpp = adset.cpp || 0;
          const weekCpp = weekAdset?.cpp || 0;
          const yestSpend = adset.fbSpend || 0;

          if (yestSpend >= 25 && yestCpp > 0) {
            const vsWeek = weekCpp > 0 ? ((yestCpp - weekCpp) / weekCpp) : null;
            const vsAccount = accountAvgCpp > 0 ? ((yestCpp - accountAvgCpp) / accountAvgCpp) : null;
            const isRising = vsWeek !== null && vsWeek > 0.15;
            const isAboveAvg = vsAccount !== null && vsAccount > 0.15;

            if (isRising || isAboveAvg) {
              flagged.push({
                level: 'adset', campaign: campaign.name, name: adset.name,
                yesterdaySpend: yestSpend, yesterdayCpp: yestCpp, weekCpp, accountAvgCpp,
                vsWeekPct: vsWeek !== null ? Math.round(vsWeek * 100) : null,
                vsAccountPct: vsAccount !== null ? Math.round(vsAccount * 100) : null,
                isRising, isAboveAvg, sales: adset.cocData?.sales || 0,
              });
            }

            for (const ad of adset.ads || []) {
              const weekAd = weekAdset?.ads?.find(a => a.name === ad.name);
              const adYestCpp = ad.cpp || 0;
              const adWeekCpp = weekAd?.cpp || 0;
              const adYestSpend = ad.fbSpend || 0;

              if (adYestSpend >= 25 && adYestCpp > 0) {
                const adVsWeek = adWeekCpp > 0 ? ((adYestCpp - adWeekCpp) / adWeekCpp) : null;
                const adVsAccount = accountAvgCpp > 0 ? ((adYestCpp - accountAvgCpp) / accountAvgCpp) : null;
                const adIsRising = adVsWeek !== null && adVsWeek > 0.15;
                const adIsAboveAvg = adVsAccount !== null && adVsAccount > 0.15;

                if (adIsRising || adIsAboveAvg) {
                  flagged.push({
                    level: 'ad', campaign: campaign.name, adset: adset.name, name: ad.name,
                    yesterdaySpend: adYestSpend, yesterdayCpp: adYestCpp, weekCpp: adWeekCpp, accountAvgCpp,
                    vsWeekPct: adVsWeek !== null ? Math.round(adVsWeek * 100) : null,
                    vsAccountPct: adVsAccount !== null ? Math.round(adVsAccount * 100) : null,
                    isRising: adIsRising, isAboveAvg: adIsAboveAvg, sales: ad.cocData?.sales || 0,
                  });
                }
              }
            }
          }
        }
      }

      flagged.sort((a, b) => (b.vsWeekPct || 0) - (a.vsWeekPct || 0));

      return {
        cocCampaignName: adAccount.cocCampaignName,
        fbAdAccountId: adAccount.fbAdAccountId,
        period: { yesterday, sevenDayStart },
        accountAvgCpp: Math.round(accountAvgCpp * 100) / 100,
        accountWeekSpend: Math.round(accountWeekSpend * 100) / 100,
        accountWeekSales,
        flagged,
      };
    }));

    res.json({ clientId: client.id, clientName: client.name, date, accounts: accountResults });
  } catch (err) {
    console.error('Insights error:', err);
    res.status(500).json({ error: err.message });
  }
});

// GET /api/prior/:clientId?startDate=YYYY-MM-DD&endDate=YYYY-MM-DD
// Returns dashboard data for the equivalent prior period
// Yesterday → day before | 7D → prior 7D | MTD → same days last month
router.get('/prior/:clientId', async (req, res) => {
  const client = getClientById(req.params.clientId);
  if (!client) return res.status(404).json({ error: 'Client not found' });

  const { startDate, endDate } = req.query;
  if (!startDate || !endDate) return res.status(400).json({ error: 'startDate and endDate required' });

  // Compute prior period
  const s = new Date(startDate + 'T12:00:00Z');
  const e = new Date(endDate + 'T12:00:00Z');
  const spanDays = Math.round((e - s) / 864e5) + 1;

  const priorEnd = new Date(s); priorEnd.setDate(s.getDate() - 1);
  const priorStart = new Date(priorEnd); priorStart.setDate(priorEnd.getDate() - (spanDays - 1));

  const ps = priorStart.toISOString().split('T')[0];
  const pe = priorEnd.toISOString().split('T')[0];

  try {
    const results = [];
    await Promise.all(client.adAccounts.map(async (adAccount) => {
      try {
        const [fbData, cocTotals] = await Promise.all([
          getFbHierarchy(client.fbAccessToken, adAccount.fbAdAccountId, ps, pe),
          getCocCampaignTotals(client.cocLoginId, client.cocPassword, adAccount.cocCampaignId, ps, pe)
        ]);
        const fbCampaignNames = fbData.map(c => c.name);
        const cocHierarchy = await getCocHierarchy(
          client.cocLoginId, client.cocPassword,
          adAccount.cocCampaignId, ps, pe, fbCampaignNames
        );
        const merged = mergeHierarchy(fbData, cocHierarchy, adAccount);
        merged.cocTotals = cocTotals;
        results.push(merged);
      } catch (err) {
        console.error('Prior period error:', err.message);
      }
    }));
    results.sort((a, b) => a.cocCampaignName.localeCompare(b.cocCampaignName));
    res.json({ clientId: client.id, startDate: ps, endDate: pe, adAccounts: results });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});


// ─── CPP Daily / 7D snapshot (sticker funnel clients) ─────────────────────────

const SHED_IDS = ['craig-revmoto-mmjeuw8s', 'craig-readynation-mmkodtu2'];

// In-memory cache — populated at 5am CT, served for the rest of the day
let cacheDaily = { date: null, data: null };
let cacheWeek  = { date: null, data: null };

function getYesterdayInTz(tz) {
  const d = new Date(new Date().toLocaleString('en-US', { timeZone: tz }));
  d.setDate(d.getDate() - 1);
  return d.toISOString().split('T')[0];
}

function dateNDaysAgoInTz(n, tz) {
  const d = new Date(new Date().toLocaleString('en-US', { timeZone: tz }));
  d.setDate(d.getDate() - n);
  return d.toISOString().split('T')[0];
}

async function fetchCppForRange(client, startDate, endDate, timeoutMs = 55000) {
  let totalSpend = 0, totalSales = 0;

  await Promise.all(client.adAccounts.map(async (adAccount) => {
    const abort = new AbortController();
    const timer = setTimeout(() => abort.abort(), timeoutMs);
    try {
      const [fbData, cocTotals] = await Promise.all([
        getFbHierarchy(client.fbAccessToken, adAccount.fbAdAccountId, startDate, endDate),
        getCocCampaignTotals(client.cocLoginId, client.cocPassword, adAccount.cocCampaignId, startDate, endDate),
      ]);
      totalSpend += fbData.reduce((s, c) => s + c.spend, 0);
      totalSales += cocTotals?.sales || 0;
    } finally {
      clearTimeout(timer);
    }
  }));

  return {
    spend: totalSpend,
    purchases: totalSales,
    cpp: totalSales > 0 ? totalSpend / totalSales : null,
  };
}

async function buildDailySnapshot(startDateOverride, endDateOverride) {
  const clients = getClients().filter(c => !SHED_IDS.includes(c.id));

  const results = await Promise.allSettled(clients.map(async (client) => {
    const tz = getClientTimezone(client);
    const start = startDateOverride || getYesterdayInTz(tz);
    const end = endDateOverride || start;
    const cppTarget = client.adAccounts?.[0]?.cppTarget || null;
    const { spend, purchases, cpp } = await fetchCppForRange(client, start, end, 90000);
    return { id: client.id, name: client.name, timezone: tz, date: start, endDate: end, spend, purchases, cpp, cppTarget };
  }));

  return results.map((r, i) => r.status === 'fulfilled'
    ? r.value
    : { id: clients[i].id, name: clients[i].name, error: r.reason?.message }
  );
}

async function buildWeekSnapshot() {
  const clients = getClients().filter(c => !SHED_IDS.includes(c.id));

  const results = await Promise.allSettled(clients.map(async (client) => {
    const tz = getClientTimezone(client);
    const end = getYesterdayInTz(tz);
    const start = dateNDaysAgoInTz(7, tz);
    const { spend, purchases, cpp } = await fetchCppForRange(client, start, end, 90000);
    return { id: client.id, spend, purchases, cpp, start, end };
  }));

  return results.map((r, i) => r.status === 'fulfilled'
    ? r.value
    : { id: clients[i].id, error: r.reason?.message }
  );
}

// Called by the 5am cron — pre-warms both caches
async function runCppSnapshot() {
  const date = getYesterdayInTz('America/Chicago');
  console.log('[CPP Snapshot] Running for', date);
  try {
    const [daily, week] = await Promise.all([buildDailySnapshot(), buildWeekSnapshot()]);
    cacheDaily = { date, data: daily };
    cacheWeek  = { date, data: week };
    console.log('[CPP Snapshot] Complete');
  } catch (err) {
    console.error('[CPP Snapshot] Error:', err.message);
  }
}

// GET /api/cpp-daily — serve from cache, fetch on demand if cache is cold
// Optional ?startDate=YYYY-MM-DD&endDate=YYYY-MM-DD bypasses cache for custom ranges
router.get('/cpp-daily', async (req, res) => {
  const yesterday = getYesterdayInTz('America/Chicago');
  const { startDate, endDate } = req.query;

  // Default path: yesterday-only, use cache
  if (!startDate && !endDate) {
    if (cacheDaily.date === yesterday && cacheDaily.data) return res.json(cacheDaily.data);
    try {
      const data = await buildDailySnapshot();
      cacheDaily = { date: yesterday, data };
      return res.json(data);
    } catch (err) {
      return res.status(500).json({ error: err.message });
    }
  }

  // Custom range — compute on demand, no cache
  const s = startDate || endDate;
  const e = endDate || startDate;
  if (!/^\d{4}-\d{2}-\d{2}$/.test(s) || !/^\d{4}-\d{2}-\d{2}$/.test(e)) {
    return res.status(400).json({ error: 'startDate and endDate must be YYYY-MM-DD' });
  }
  try {
    const data = await buildDailySnapshot(s, e);
    res.json(data);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// GET /api/cpp-7day — serve from cache, fetch on demand if cache is cold
router.get('/cpp-7day', async (req, res) => {
  const date = getYesterdayInTz('America/Chicago');
  if (cacheWeek.date === date && cacheWeek.data) return res.json(cacheWeek.data);
  try {
    const data = await buildWeekSnapshot();
    cacheWeek = { date, data };
    res.json(data);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ─── Sheds CPL proxy ──────────────────────────────────────────────────────────
// sheds.2by4llc.com has its own codebase + API. The launchpad shows yesterday's
// CPL per shed client; we proxy through here so the browser only needs the dash
// password and we can cache to avoid hammering Meta.
//
// Upstream contract (from 2by4-sheds/server.js):
//   GET /api/rollup?startDate=YYYY-MM-DD&endDate=YYYY-MM-DD
//   Auth: header `x-dash-password` (sheds has its own DASH_PASSWORD distinct
//   from this service's). Returns { startDate, endDate, clients:
//   [{ name, accountId, insights, leads, cpl, error }] }.

const SHEDS_BASE_URL = process.env.SHEDS_BASE_URL || 'https://sheds.2by4llc.com';
const SHEDS_PASSWORD = process.env.SHEDS_DASH_PASSWORD || process.env.DASH_PASSWORD;
const SHEDS_CACHE_TTL_MS = 5 * 60 * 1000;
let shedsCplCache = { key: null, ts: 0, data: null };

router.get('/sheds/cpl-yesterday', async (req, res) => {
  const yesterday = getYesterdayInTz('America/Chicago');
  const now = Date.now();

  if (shedsCplCache.data && shedsCplCache.key === yesterday && (now - shedsCplCache.ts) < SHEDS_CACHE_TTL_MS) {
    return res.json(shedsCplCache.data);
  }

  const headers = SHEDS_PASSWORD ? { 'x-dash-password': SHEDS_PASSWORD } : {};

  try {
    const r = await axios.get(`${SHEDS_BASE_URL}/api/rollup`, {
      headers,
      params: { startDate: yesterday, endDate: yesterday },
      timeout: 25000,
    });

    const upstream = Array.isArray(r.data?.clients) ? r.data.clients : [];
    const rows = upstream.map((c) => {
      if (c.error) return { name: c.name, accountId: c.accountId, error: c.error };
      const spend = c.insights?.spend != null ? Number(c.insights.spend) : null;
      return {
        name: c.name,
        accountId: c.accountId,
        spend,
        results: c.leads ?? null,
        costPerResult: c.cpl ?? null,
        resultType: 'leads',
      };
    });

    shedsCplCache = { key: yesterday, ts: now, data: rows };
    res.json(rows);
  } catch (err) {
    const upstreamMsg = err.response?.data?.error || err.message;
    res.status(502).json({ error: `Sheds upstream: ${upstreamMsg}` });
  }
});

// ─── TODAY: Google Calendar + Drive (Phase 2 of the launchpad) ───────────────

router.get('/today/meetings', async (req, res) => {
  try {
    const meetings = await googleSvc.getTodayMeetings();
    res.json({ meetings, asOf: new Date().toISOString() });
  } catch (err) {
    console.error('[today/meetings]', err.message);
    res.status(500).json({ error: err.message });
  }
});

router.get('/today/tasks', async (req, res) => {
  try {
    const { tasks, asOf } = await googleSvc.getOpenTasks();
    res.json({ tasks, asOf });
  } catch (err) {
    console.error('[today/tasks]', err.message);
    res.status(500).json({ error: err.message });
  }
});

// GET /api/today/folders — all configured client folders (sticker + shed).
// Used by the Clients browser so zero-task clients still appear.
router.get('/today/folders', async (req, res) => {
  try {
    const folders = await googleSvc.getClientFolders();
    res.json({
      folders: folders.map(f => ({ name: f.name, type: f.type })),
    });
  } catch (err) {
    console.error('[today/folders]', err.message);
    res.status(500).json({ error: err.message });
  }
});

// Diagnostic: shows what the SA can see — folder list, CLAUDE.md candidates,
// detected ## headings, parsed task count. Hit in browser to debug empty results.
router.get('/today/debug', async (req, res) => {
  try {
    const snap = await googleSvc.debugSnapshot();
    res.json(snap);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ─── TODAY: writes (toggle + add + upload) ───────────────────────────────────

// Resolve a client name from the request to a Drive folder; throws 4xx on miss.
async function resolveClientFolder(req, res) {
  const name = (req.body && req.body.client) || '';
  if (!name) {
    res.status(400).json({ error: 'client (folder name) required' });
    return null;
  }
  const folder = await googleSvc.findClientFolderByName(name);
  if (!folder) {
    res.status(404).json({ error: `Client folder "${name}" not found` });
    return null;
  }
  return folder;
}

// POST /api/today/tasks/toggle  { client, raw }
// Flip the matching `- [ ]` ↔ `- [x]` line in the client's CLAUDE.md.
router.post('/today/tasks/toggle', async (req, res) => {
  try {
    const folder = await resolveClientFolder(req, res);
    if (!folder) return;
    const raw = req.body && req.body.raw;
    if (!raw) return res.status(400).json({ error: 'raw (original task line) required' });

    const content = await googleSvc.fetchClaudeMd(folder.id);
    if (!content) return res.status(404).json({ error: `No CLAUDE.md in "${folder.name}"` });

    const { content: next, changed } = toggleCheckboxLine(content, raw);
    if (!changed) return res.status(404).json({ error: 'Task line not found in CLAUDE.md (may be stale)' });

    await googleSvc.writeClaudeMdContent(folder.id, next);
    res.json({ ok: true, client: folder.name });
  } catch (err) {
    console.error('[today/tasks/toggle]', err);
    res.status(500).json({ error: err.message });
  }
});

// POST /api/today/tasks/add  { client, text }
// Append `- [ ] text` to the first task-heading section (creating `## Open Items` if none).
router.post('/today/tasks/add', async (req, res) => {
  try {
    const folder = await resolveClientFolder(req, res);
    if (!folder) return;
    const text = (req.body && req.body.text || '').trim();
    if (!text) return res.status(400).json({ error: 'text required' });

    const content = await googleSvc.fetchClaudeMd(folder.id);
    if (content == null) return res.status(404).json({ error: `No CLAUDE.md in "${folder.name}"` });

    const { content: next, added, createdSection } = appendOpenItem(content, text);
    if (!added) return res.status(400).json({ error: 'Nothing to add' });

    await googleSvc.writeClaudeMdContent(folder.id, next);
    res.json({ ok: true, client: folder.name, createdSection: !!createdSection });
  } catch (err) {
    console.error('[today/tasks/add]', err);
    res.status(500).json({ error: err.message });
  }
});

// POST /api/today/tasks/refresh
// Bust the tasks cache and return a fresh snapshot. No body.
router.post('/today/tasks/refresh', async (req, res) => {
  try {
    googleSvc.invalidateTasksCache();
    const { tasks, asOf } = await googleSvc.getOpenTasks();
    res.json({ tasks, asOf });
  } catch (err) {
    console.error('[today/tasks/refresh]', err.message);
    res.status(500).json({ error: err.message });
  }
});

// POST /api/today/upload  { client, filename, fileMimeType, fileBase64?, fileText?, todayDate? }
// Proxy to Brain's meeting-recap agent. Returns the draft for user review.
// Does NOT write anything yet — `/today/upload/commit` is the second step.
const BRAIN_BASE_URL = process.env.BRAIN_BASE_URL || 'https://brain.2by4llc.com';
const BRAIN_PASSWORD = process.env.DASH_PASSWORD; // shared between dash + brain

router.post('/today/upload', async (req, res) => {
  try {
    const folder = await resolveClientFolder(req, res);
    if (!folder) return;
    const { filename, fileMimeType, fileBase64, fileText, todayDate } = req.body || {};
    if (!filename) return res.status(400).json({ error: 'filename required' });
    if (!fileBase64 && !fileText) return res.status(400).json({ error: 'fileBase64 or fileText required' });

    const r = await axios.post(`${BRAIN_BASE_URL}/api/agents/meeting-recap`, {
      clientName: folder.name,
      fileText, fileBase64, fileMimeType, todayDate,
    }, {
      headers: { 'x-dash-password': BRAIN_PASSWORD },
      timeout: 120000,
    });

    const { recapMarkdown, openItems } = r.data || {};
    if (typeof recapMarkdown !== 'string' || !Array.isArray(openItems)) {
      return res.status(502).json({ error: 'Brain returned malformed response', upstream: r.data });
    }

    // Suggest a filename: <today>-<sanitized original stem>.md
    const today = (todayDate && /^\d{4}-\d{2}-\d{2}$/.test(todayDate)) ? todayDate : new Date().toISOString().slice(0, 10);
    const stem = String(filename).replace(/\.[^.]+$/, '').toLowerCase()
      .replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 60) || 'meeting';
    const suggestedFilename = `${today}-${stem}.md`;

    res.json({ client: folder.name, recapMarkdown, openItems, suggestedFilename });
  } catch (err) {
    const upstream = err.response?.data?.error || err.message;
    console.error('[today/upload]', upstream);
    res.status(502).json({ error: `Brain: ${upstream}` });
  }
});

// POST /api/today/upload/commit  { client, filename, recapMarkdown, openItems[] }
// Persist user-approved recap: write the .md file to the client's `meetings/`
// folder and append the open items to its CLAUDE.md.
router.post('/today/upload/commit', async (req, res) => {
  try {
    const folder = await resolveClientFolder(req, res);
    if (!folder) return;
    const { filename, recapMarkdown, openItems } = req.body || {};
    if (!filename || typeof recapMarkdown !== 'string') {
      return res.status(400).json({ error: 'filename and recapMarkdown required' });
    }
    const items = Array.isArray(openItems) ? openItems : [];

    // 1) Write the recap file under <client>/meetings/
    const meetingsFolder = await googleSvc.ensureSubfolder(folder.id, 'meetings');
    const safeName = filename.endsWith('.md') ? filename : `${filename}.md`;
    const file = await googleSvc.createFileInFolder(
      meetingsFolder.id, safeName, 'text/markdown', Buffer.from(recapMarkdown, 'utf8')
    );

    // 2) Append open items to CLAUDE.md (if any)
    let added = 0;
    if (items.length) {
      const content = await googleSvc.fetchClaudeMd(folder.id);
      if (content != null) {
        const { content: next, added: n } = appendOpenItems(content, items);
        if (n > 0) {
          await googleSvc.writeClaudeMdContent(folder.id, next);
          added = n;
        }
      }
    }

    res.json({ ok: true, client: folder.name, file: { id: file.id, name: file.name, link: file.webViewLink || null }, openItemsAdded: added });
  } catch (err) {
    console.error('[today/upload/commit]', err);
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
module.exports.runCppSnapshot = runCppSnapshot;
